
CREATE TABLE USERS
(
  ID INT PRIMARY KEY NOT NULL IDENTITY,
  LAST_NAME VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  EMAIL VARCHAR(50),
  PASSWORD VARCHAR(20),
  ROW_STATUS INT DEFAULT 0 NOT NULL
);

CREATE TABLE CATEGORY_TYPE
(
  ID INT IDENTITY PRIMARY KEY,
  NAME VARCHAR(50),
  ROW_STATUS INT DEFAULT 0
);

CREATE TABLE CATEGORY
(
  ID INT IDENTITY PRIMARY KEY NOT NULL,
  NAME VARCHAR(50),
  CATEGORY_TYPE_ID INT NOT NULL,
  ROW_STATUS INT DEFAULT 0
);


